COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://flaskuser:<your password>@<database endpoint>/lab4d'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://flaskuser:<your password>@<database endpoint>/lab4d'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: admin
  MYSQL_ROOT_PASSWORD: password
